sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 'pypy'
install: pip install tox-travis
script: tox
cache:
  directories:
  - $HOME/.cache/pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
